<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'php_boilerplate\\plugins\\formbuilder\\_plugin' => '_plugin.php',
                'php_boilerplate\\plugins\\formbuilder\\formbuilder' => 'FormBuilder.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . '/' . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd