<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'marshall\\core\\basecontroller' => '/core/BaseController.php',
                'marshall\\core\\nonpersistentbean' => '/core/NonPersistentBean.php',
                'marshall\\core\\menu' => '/core/Menu.php',
                'marshall\\core\\menuitem' => '/core/MenuItem.php',
                'marshall\\core\\baseplugin' => '/core/BasePlugin.php'                
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
require_once(__DIR__ . '/f3_utility/auto_include_files.php');
// hopefully auto pull in any other autoload files in the plugins directories
include_once(__DIR__ . '/f3_utility/find_autoload.php');
// @codeCoverageIgnoreEnd